### ISSUE TITLE
Problems with assetgrid container

### ISSUE THREAD

**Issue by second2falcon** [assetgrid/assetgridapp#34]
**Describe the bug**
When I use the "standard"/example docker compose found in the docs, I get an error which continuously makes the container exit/stop.

**To Reproduce**
1. Make the docker-compose.yml with the example found in the docs or make a new stack in Portainer.
2. Start the stack/use docker compose up
3. Wait
4. See error in logs (either via CMD or Portainer GUI)

**Expected behavior**
Assetgrid container starts

**Desktop (please complete the following information):**
 - OS: macOS Monterey and Windows 10
 - Browser: Brave
 - Version: 1.44.108

**Server (please complete the following information):**
 - OS: Debian 11 with Proxmox kernel
 - Docker + Portainer
 - Docker Version: 20.10.18

**Additional context**
Logs attatched
[_assetgrid_logs.txt](https://github.com/assetgrid/assetgridapp/files/9767636/_assetgrid_logs.txt)

**Comment by alex6480** [comment]
There is an issue with your database configuration.
I have added support for Sqlite, which is much simpler to configure. Could you try this docker-compose instead? Make sure to pull the newest version of the image, otherwise it won't be supported.

````yaml
version: "3.1"
services:
  assetgrid:
    image: assetgrid/assetgrid
    container_name: assetgrid
    volumes:
      - assetgrid-data:/usr/share/assetgrid/assetgrid_data
    ports:
      - 80:8080

volumes:
  assetgrid-data:
````
