### ISSUE TITLE
First connection Defaul email and Password?

### ISSUE THREAD

**Issue by mariushosting** [assetgrid/assetgridapp#35]
What is the default email and password to log in for the first time?

**Comment by alex6480** [comment]
There is no default login. If a user doesn't exist, the login page redirect to a signup page, that currently looks almost exactly like the login page. So I don't blame you if you didn't notice that happened.

You first enter your desired login on the signup page, which will then redirect to the login page where you must enter it again to actually login. After the first user has been created, the signup page is disabled.

If you accidentally created a user and don't remember the credentials, you will need to reset the database.

**Comment by mariushosting** [comment]
The issue, is that. It's not working. Even if I add all the credentials, the page is frozen. Nothing happens.

![notwork](https://user-images.githubusercontent.com/37554361/195690639-6adfc2e4-ef78-44c1-9122-b5bfc7be25e5.png)

**Comment by mariushosting** [comment]
Ok I found the issue. The container does not work with mariaDB. Instead it works with SQLite.

Here is my docker compose that does not work and does not redirect to the signup page, only sign in page.

```
version: "3.1"
services:
  db:
    image: mariadb:latest
    container_name: Assetgrid-DB
    restart: always
    volumes:
      - /volume1/docker/assetgridatabase:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: assetgrid
      MYSQL_USER: assetgrid
  assetgrid:
    image: assetgrid/assetgrid
    container_name: Assetgrid
    restart: always
    links:
      - db:db
    environment:
      Provider: "MySQL"
      "ConnectionStrings:MySQL": "Server=db;Database=assetgrid;Uid=assetgrid;Pwd=secret"
    ports:
      - 5160:8080
```
