### ISSUE TITLE
Docker multi-arch support

### ISSUE THREAD

**Issue by Just5KY** [assetgrid/assetgridapp#38]
**Is your feature request related to a problem? Please describe.**
There is no arm64 or arm32 docker image.

**Describe the solution you'd like**
Add the following in GitHub workflow.

```yml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
      .
      .
      .

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64  #,linux/arm/v7,linux/arm/v6, linux/386, linux/ppc64le,linux/s390x
        .
        .
```
You also might have to change some stuff in the backend and frontend buildings

**Describe alternatives you've considered**
No other alternatives

**Additional context**
![image](https://user-images.githubusercontent.com/71321862/195719083-e7127ccd-e094-4b11-ae20-dea5f4cb0842.png)
